[package]
name = "casper-sse-client"
version.workspace = true
edition.workspace = true

[lib]

[[bin]]
name = "casper-sse-client"

[dependencies]
reqwest = { version = "0.11.26", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
