[package]
name = "casper-sse-client"
version.workspace = true
edition.workspace = true

[lib]

[[bin]]
name = "casper-sse-client"

[dependencies]
reqwest = "0.11.26"
tokio = { version = "1", features = ["full"] }
