[package]
name = "kairos-verifier-risc0-lib"
version.workspace = true
edition.workspace = true
license.workspace = true

disable-dev-mode = [ "risc0-zkvm/disable-dev-mode" ]
cuda = [ "risc0-zkvm/cuda", "disable-dev-mode" ]
metal = [ "risc0-zkvm/metal", "disable-dev-mode" ]

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "=0.21.0"
kairos-circuit-logic = { path = "../kairos-circuit-logic", features = ["serde"] }
kairos-prover-server-lib = { path = "../kairos-prover-server-lib" }

[target.'cfg(windows)'.dev-dependencies]
# dlmalloc wants windows-sys 0.52.0
# which in turn wants windows-targets 0.52.4
# which in turn for whatever reason locks some
# of the following targets to 0.52.5
# and that causes the build to fail
windows_aarch64_gnullvm = "=0.52.4"
windows_aarch64_msvc = "=0.52.4"
windows_i686_gnu = "=0.52.4"
windows_i686_msvc = "=0.52.4"
windows_x86_64_gnu = "=0.52.4"
windows_x86_64_gnullvm = "=0.52.4"
windows_x86_64_msvc = "=0.52.4"
