[package]
name = "kairos-verifier-risc0-lib"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
disable-dev-mode = [ "risc0-zkvm/disable-dev-mode" ]

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "=0.21.0", default-features = false }
kairos-circuit-logic = { path = "../kairos-circuit-logic", features = ["serde"], default-features = false }
rkyv = { version = "0.7", default-features = false, features = ["size_32", "archive_le", "alloc", "validation"] }
