[package]
name = "zk-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circuits = { path = "../circuits" }
risc0-zkvm = { version = "0.21.0", features=["prove"] }
risc0-groth16 = { version = "0.21.0" }
serde = "1.0"
kairos-trie = { git="https://github.com/cspr-rad/kairos-trie", default-features=false }
types = {path="../types", default-features=false}
sha2 = {version="0.10", default-features = false}
bumpalo = "3"

[features]
# If this feature is used, the groth16 wrapper will be used, otherwise the default prover will be used.
groth16 = []
