[package]
name = "contract"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-contract = {version="4.0.0", features=["std", "test-support"]}
casper-types = {version="4.0.0", default-features=false}
base64 = { version = "0.20.0", default-features = false, features = ["alloc"] }
contract-types = {path="../../contract-types"}
bincode = "1.3.3"


[build]
target = "wasm32-unknown-unknown"

[[bin]]
name = "deposit-contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true