[package]
name = "deposit-contract-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
base64 = { version = "0.21.2", default-features = false, features = ["alloc"] }
casper-engine-test-support = {git = "https://github.com/casper-network/casper-node", branch="release-1.5.6", default-features=false}
casper-execution-engine = {git = "https://github.com/casper-network/casper-node", branch="release-1.5.6", default-features=false}
casper-contract = {git = "https://github.com/casper-network/casper-node", branch="release-1.5.6", default-features=false}
casper-types = {git = "https://github.com/casper-network/casper-node", branch="release-1.5.6", default-features=false}
dotenv = "0.15.0"

[[test]]
name = "kairos_contract_tests"
path = "src/integration_tests.rs"

[dependencies]
lazy_static = "1.4.0"
