[workspace]
resolver = "2"

members = [
  "casper-deploy-notifier",
  "kairos-cli",
  "kairos-server",
]

[workspace.package]
name = "kairos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

