[workspace]
resolver = "2"

members = [
  "kairos-cli",
  "kairos-crypto",
  "kairos-server",
  "kairos-tx",
  "kairos-test-utils",
]

[workspace.package]
name = "kairos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
