[workspace]
resolver = "2"

members = [
  "kairos-cli",
  "kairos-server",
  "kairos-tx",
  "contracts/contract-types",
  "contracts/deposit-contract-tests",
]

[workspace.package]
name = "kairos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
