[workspace]
resolver = "2"

members = [
  "casper-deploy-notifier",
  "kairos-cli",
  "kairos-crypto",
  "kairos-server",
  "kairos-tx",
  "kairos-test-utils",
  "demo-contract-tests",
  "kairos-contracts/demo-contract/contract-utils"
]

[workspace.package]
name = "kairos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
casper-client = "2.0"
casper-types = "4.0"
casper-client-types = { package = "casper-types", version = "3.0" }
casper-hashing = "3.0"
casper-event-standard = "0.5"
casper-event-toolkit = { git = "https://github.com/koxu1996/casper-event-toolkit", branch = "test" }
