[workspace]
resolver = "2"
# Currently guest only exists for the workspace configuration not to break
members = ["methods/native-cspr-tx", "methods/guest", "kairos-risc0-types", "kairos-delta-tree", "node", "layer-one-utils", "kairos-risc0-types", "kairos-delta-tree"]
exclude = ["contracts"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3