[package]
name = "methods"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
risc0-binfmt = "=1.0.3"
kairos-verifier-risc0-lib = { path = "../kairos-verifier-risc0-lib", default-features = false }
