[package]
name = "methods"
version.workspace = true
edition.workspace = true
license.workspace = true

[profile.release]
debug = 0
opt-level = 3
overflow-checks = false
lto = true
strip = true
debug-assertions = false
panic = "abort"
codegen-units = 1

[build-dependencies]
risc0-build = "=0.21.0"
dotenvy = "0.15"
hex = "0.4"

[package.metadata.risc0]
methods = ["guest"]
