[package]
name = "deposit-session"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-contract.workspace = true
casper-types.workspace = true

[[bin]]
name = "deposit-session"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
