[package]
name = "deposit-session"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-contract = {git="https://github.com/cspr-rad/casper-node", branch="kairos-demo-1.5.6"}
casper-types = {git="https://github.com/cspr-rad/casper-node", branch="kairos-demo-1.5.6"}

[[bin]]
name = "deposit-session"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
