[package]
name = "malicious-reader"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-contract.workspace = true
casper-types.workspace = true

[[bin]]
name = "malicious-reader"
path = "src/main.rs"
bench = false
doctest = false
test = false
