[package]
name = "contract-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.196", default-features=false}
casper-types = {git = "https://github.com/cspr-rad/casper-node", branch="kairos-feat-2.0"}
