[package]
name = "deposit-session"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = {version="4.0.0", features=["test-support"]}
casper-types = "4.0.0"

[[bin]]
name = "deposit-session"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true