[package]
name = "deposit-session"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", features=["test-support"]}
casper-types = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0"}

[[bin]]
name = "deposit-session"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true