[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
tornado-tree-rs = {path="../tornado-tree-rs"}
kairos-risc0-types = {path="../kairos-risc0-types"}

methods = { path = "../methods" }
risc0-zkvm = "0.20.1"
env_logger = "0.11.2"
serde = "1.0.197"
serde_json = "1.0.114"