// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use casper_types::{account::AccountHash, U512};
use kairos_types::transfer::{
    LayerTwoAccount, LayerTwoTransaction, MockLayerOneState, MockLayerTwoState,
};
use methods::{KAIROS_ELF, KAIROS_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde_json;

fn main() {
    env_logger::init();
    // For example:
    let x: u32 = 10;
    let y: u32 = 10;
    let env = ExecutorEnv::builder()
        .write(&x)
        .unwrap()
        .write(&y)
        .unwrap()
        .build()
        .unwrap();
    let prover = default_prover();
    let receipt = prover.prove_elf(env, KAIROS_ELF).unwrap();
    let new_layer_one_state: MockLayerOneState =
        serde_json::from_slice(&receipt.journal.decode::<Vec<u8>>().unwrap().to_vec()).unwrap();
    receipt.verify(KAIROS_ID).unwrap();
    println!("New L1 state: {:?}", &new_layer_one_state);
}

/* Circuit objective
    * Circuit design
        * take a set of transfers as input and generate a batch proof
            * verify all transaction signatures
            * verify that the merkle proof for every leaf is valid
            * if state transitions are not applied inside the circuit:
                * append the merkle tree w. said transactions and output the new root hash
            * else:
                * updated balances as public output (together with the new root)

    * On-chain interaction
        * post the root hash & proof to the L1

    * Q&A
        * What's the point in having a circuit that proves that a root hash results from a valid state transitions (e.g. a set of valid transactions w. already verified signatures) ?
            * reduced L1 workload as signatures don't have to be verified on-chain, but instead only a single proof
*/
