// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{KAIROS_ELF, KAIROS_ID};
use risc0_types::State;
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde_json;

fn main() {
    env_logger::init();
    // For example:
    let x: u32 = 10;
    let y: u32 = 10;
    let env = ExecutorEnv::builder()
        .write(&x)
        .unwrap()
        .write(&y)
        .unwrap()
        .build()
        .unwrap();
    let prover = default_prover();
    let receipt = prover.prove_elf(env, KAIROS_ELF).unwrap();
    let _output: State =
        serde_json::from_slice(&receipt.journal.decode::<Vec<u8>>().unwrap().to_vec()).unwrap();
    receipt.verify(KAIROS_ID).unwrap();
    assert!(_output.x == x);
    assert!(_output.y == y);
}
