[package]
name = "temp-e2e-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-client = "2.0.0"
casper-types = "3.0.0"

risc0-zkvm = {version="=0.21.0", default-features=false, features=["prove"]}
serde = {version="1", default-features=false, features=["derive"]}
kairos-trie = {git="https://github.com/cspr-rad/kairos-trie", default-features=false, features=["serde"]}
kairos-circuit-logic = {path="../kairos-prover/kairos-circuit-logic", features=["serde"]}
methods = {path="../kairos-prover/methods"}
serde-json-wasm = "1"
rand = "0.8"
wasm-opt = "0.116"
sha2 = {version = "0.10", default-features = false}
tokio = {version="1.36.0", features=["full"]}
