[workspace]
resolver = "2"

members = [
  "demo-contract/malicious-reader",
  "demo-contract/malicious-session",
  "demo-contract/deposit-session",
  "demo-contract/contract",
]

[workspace.package]
name = "kairos-contracts"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
