[package]
name = "kairos-l1-state-replicator"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]

[[bin]]
name = "kairos-l1-state-replicator"

[dependencies]
casper-client = "2.0.0"
tokio = { version = "1", features = ["full"] }
