[package]
name = "risc0-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version="1.0.111", features = ["alloc"], default-features=false }
serde = { version="1.0.195", features = ["derive", "alloc"], default-features = false }
