[package]
name = "verifier-contract-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.21.2", default-features = false, features = ["alloc"] }
casper-engine-test-support = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", default-features=false}
casper-execution-engine = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", default-features=false}
casper-contract = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", default-features=false}
casper-types = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", default-features=false}
methods = { path = "../../methods" }
risc0-zkvm = {version="0.21.0", default-features=false, features=["prove"]}
kairos-risc0-types = {path="../../kairos-risc0-types", features=["kairos-delta-tree"]}
dotenv = "0.15.0"
serde_json = "1.0.114"
lazy_static = "1.4.0"
#tracing-subscriber = { version = "0.3", features = ["env-filter"] }


[[test]]
name = "kairos_verifier_tests"
path = "src/integration_tests.rs"