[package]
name = "profiling"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "=1.0.1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

kairos-circuit-logic = { path = "../kairos-circuit-logic", features = ["serde"], default-features = false }
kairos-trie = { git = "https://github.com/cspr-rad/kairos-trie", features = ["serde"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
