[[bin]]
name = "kairos-cli"
path = "bin/main.rs"
version = "0.1.0"
test = false
bench = false

[package]
name = "kairos-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-types = { version = "4.0.1", features = ["std"] } # TODO: Change `std` -> `std-fs-io` in the future version.
clap = { version = "4.4.18", features = ["derive"] }
hex = "0.4.3"
thiserror = "1.0.56"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
