[package]
name = "sync-service"
version = "0.1.0"
edition = "2021"

[dependencies]
kairos-risc0-types = {path="../kairos-risc0-types"}
casper-types = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6"}
tokio = {version="1.36.0", features=["full"]}
methods = { path = "../methods" }
risc0-zkvm = "0.20.1"
env_logger = "0.11.2"
serde = {version="1.0.197", features=["derive"]}
serde_json = "1.0.114"