[package]
name = "kairos-risc0-types"
version = "0.1.0"
edition = "2021"

[dependencies]
#risc0-zkvm = "0.20.1"
serde = {version="1.0.197", features=["derive"]}
serde_json = "1.0.114"
tornado-tree-rs = {path="../tornado-tree-rs", optional=true}
casper-types = {git = "https://github.com/cspr-rad/casper-node", branch="kairos-feat-2.0"}

[features]
tornado-tree = ["tornado-tree-rs"]