[package]
name = "malicious-reader"
workspace.version = true
workspace.edition = true
workspace.license = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract = "4.0.0"
casper-types = "4.0.0"

[[bin]]
name = "malicious-reader"
path = "src/main.rs"
bench = false
doctest = false
test = false