[package]
name = "contract"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-contract.workspace = true
casper-contract-no-std-helpers.workspace = true
casper-types.workspace = true
casper-event-standard.workspace = true
contract-utils = { path = "../contract-utils" }

[build]
target = "wasm32-unknown-unknown"

[[bin]]
name = "demo-contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
