[package]
name = "contract"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-contract = {git="https://github.com/cspr-rad/casper-node", branch="kairos-demo-1.5.6", features=["std", "test-support"]}
casper-types = {git="https://github.com/cspr-rad/casper-node", branch="kairos-demo-1.5.6", default-features=false}
casper-event-standard= {git="https://github.com/cspr-rad/casper-event-standard", branch="kairos-demo-1.5.6", default-features=false}
base64 = { version = "0.20.0", default-features = false, features = ["alloc"] }
bincode = "1.3.3"


[build]
target = "wasm32-unknown-unknown"

[[bin]]
name = "demo-contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
