[package]
name = "kairos-tx"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]

[dependencies]
num-traits = "0.2"
rasn = { version = "0.12", default-features = false, features = ["macros"] }
sha2 = "0.10"

[features]
default = ["std"]
std = []
