[package]
name = "kairos-prover-risc0-server"
version.workspace = true
edition.workspace = true
license.workspace = true


[features]
default = []
write-test-proofs = [ "disable-dev-mode" ]
disable-dev-mode = [ "risc0-zkvm/disable-dev-mode", "kairos-verifier-risc0-lib/disable-dev-mode" ]
cuda = [ "risc0-zkvm/cuda",  "disable-dev-mode" ]
metal = [ "risc0-zkvm/metal", "disable-dev-mode" ]
prove = [ "risc0-zkvm/prove" ]

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version="=1.0.3", default-features=false }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

kairos-circuit-logic = { path = "../kairos-circuit-logic", features = ["serde"], default-features = false }
kairos-verifier-risc0-lib = { path = "../kairos-verifier-risc0-lib" }
kairos-trie = { git = "https://github.com/cspr-rad/kairos-trie", features = ["serde"] }

tokio = { version = "1", features = ["rt-multi-thread", "tracing", "macros"] }
axum = { version = "0.7", features = ["tracing"] }
axum-extra = { version = "0.9", features = [
    "typed-routing",
    "typed-header",
    "json-deserializer",
] }

dotenvy = "0.15"

serde = { version = "1", features = ["derive"] }
# TODO switch to borsh
serde_json = "1.0"


[dev-dependencies]
kairos-circuit-logic = { path = "../kairos-circuit-logic", features = ["serde", "test-logic", "arbitrary" ], default-features = false }
test-strategy = { version = "0.3" }
proptest = { version = "1" }
casper-types = "4.0"
