[package]
name = "verifier-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", features=["std"]}
casper-types = {git = "https://github.com/jonas089/casper-node", branch="kairos-1.5.6-risc0", default-features=false}
serde-json-wasm = "1.0.1"

[build]
target = "wasm32-unknown-unknown"

[[bin]]
name = "verifier-contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true