[package]
name = "contract-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
test = false
bench = false
doctest = false

[dependencies]
casper-types.workspace = true
casper-event-standard = { version = "0.5", default-features = false }
