[workspace]
resolver = "2"

members = [
	"deposit-contract-tests", "verifier-contract-tests"
]

exclude = [
	"deposit-contracts",
	"verifier-contract"
]

[workspace.package]
name = "kairos-contract"
version = "0.1.0"
edition = "2021"
