[workspace]
resolver = "2"

members = [
	"deposit-contract-tests",
	"contract-types"
]

exclude = [
	"deposit-contracts"
]

[workspace.package]
name = "kairos-contract"
version = "0.1.0"
edition = "2021"
