[package]
name = "kairos-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
kairos-tx = { path = "../kairos-tx" }
