[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde_json = { version="1.0.111", features = ["alloc"], default-features=false }
risc0-types = { path="../risc0-types" }