[package]
name = "host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "=0.21.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
