[package]
name = "host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "=0.19.1"
serde = "1.0"
cargo-platform = "=0.1.5"
home = "=0.5.5"
