[package]
name = "contract"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = {git = "https://github.com/jonas089/casper-node", rev="0bcc25f4a203be4e78eed679b54127ab1ed848ab", default-features=false}
casper-types = {git = "https://github.com/jonas089/casper-node", rev="0bcc25f4a203be4e78eed679b54127ab1ed848ab"}
contract-types = {path = "../contract-types"}
serde-json-wasm = "1.0.1"

[build]
target = "wasm32-unknown-unknown"

[[bin]]
name = "deposit-contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true

