[package]
name = "contract-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.197"
casper-types = {git = "https://github.com/casper-network/casper-node", branch="release-1.5.6", default-features=false}