[package]
name = "kairos-circuit-logic"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["std", "arbitrary", "test-logic", "rkyv"] 
std = []
serde = ["dep:serde", "kairos-trie/serde"]
asn1 = ["dep:kairos-tx"]
rkyv = ["dep:rkyv"]
arbitrary = ["dep:proptest", "dep:test-strategy", "std", "test-logic"]
test-logic = []

[dependencies]
kairos-tx = { path = "../../kairos-tx", default-features = false, optional = true }
kairos-trie = { git = "https://github.com/cspr-rad/kairos-trie", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "alloc"], optional = true }
sha2 = { version = "0.10", default-features = false }
rkyv = { version = "0.7", default-features = false, features = ["size_32", "archive_le", "alloc", "validation"], optional = true }

# dev dependencies enabled by arbitrary
test-strategy = { version = "0.3", optional = true }
proptest = { version = "1", optional = true }

[dev-dependencies]
test-strategy = { version = "0.3" }
proptest = { version = "1" }
