[package]
name = "kairos-test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]

log = "*"
tokio = { version = "*", features = [ "full", "macros" ] }
env_logger = "*"
tempfile = "*"
nom = "*"

[dev-dependencies]
casper-client = "2"
anyhow = "*"
