[package]
name = "kairos-test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]

tokio = { version = "*", features = [ "full", "tracing", "macros" ] }
tempfile = "*"
tracing = "0.1"
nom = "*"

[dev-dependencies]
casper-client = "2"
anyhow = "*"
