[workspace]
resolver = "2"

members = [
  "malicious-reader",
  "malicious-session",
  "deposit-session",
  "contract"
]

[workspace.package]
name = "deposit-contracts"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"