name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  pull-requests: write
  checks: write

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14 ]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: format
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.treefmt

      - name: audit
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.audit

      - name: lint
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.lint

      - name: coverage
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --out-link coverage-result --show-trace .#checks.x86_64-linux.coverage-report

      - name: report coverage
        if: matrix.os == 'ubuntu-latest'
        uses: 5monkeys/cobertura-action@v13
        with:
          path: coverage-result/cobertura.xml
          minimum_coverage: 60

      - name: kairos-contracts x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos-contracts

      - name: kairos-contracts x86_64-darwin
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.kairos-contracts

      - name: kairos-contracts aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.kairos-contracts

      - name: kairos x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos

      - name: kairos aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.kairos

      - name: kairos-tx-no-std x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos-tx-no-std

      - name: kairos-tx-no-std aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.kairos-tx-no-std
      - name: kairos-prover x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos-prover

      - name: kairos-prover aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.kairos-prover

      - name: kairos-prover x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos-prover

      - name: verify-kairos-host-configuration-test x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.verify-kairos-host-configuration-test

      - name: kairos-end-to-end-test x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.kairos-end-to-end-test

