name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-14 ]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: check
        run: nix flake check -L --show-trace

      - name: kairos x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos

      - name: kairos x86_64-darwin
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.kairos

      - name: kairos aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.kairos

      - name: kairos-prover x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos-prover

      - name: kairos-prover x86_64-darwin
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.kairos-prover

      - name: kairos-prover aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.kairos-prover

      - name: kairos-prover x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.kairos-prover

      - name: verify-kairos-host-configuration-test x86_64-linux
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.verify-kairos-host-configuration-test

