name: extra-check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # https://github.com/cspr-rad/kairos/pull/61#issuecomment-2035637388
  build-kairos-tx-without-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build no_std version of `kairos-tx`
        run: cargo build -p kairos-tx --no-default-features
