[profile.ci]
fail-fast = false
failure-output = "immediate-final"
slow-timeout = { period = "30s", terminate-after = 4, grace-period = "10s" }

[profile.ci.junit]
path = "/tmp/junit.xml"
report-name = "Kairos"
